# Site
name: "Crafty Developers"
description: "Crafty Developers are passionate developers who also has a passion for teaching others on how to code or being creative!"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
email: "icuemike@outlook.com"
mailchimp-list: ""

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-admin

authors:
  michael:
    name: icueMike
    site: https://www.craftydevs.net
    avatar: /assets/images/memike.png
    bio: "Hi, I am Michael, the developer of CraftyDevs. I hope you like it!"
    email: icuemike@craftydevs.net
    twitter: https://twitter.com/icuemike

  landon:
    name: miceCODE
    site: https://www.craftydevs.net
    avatar: /assets/images/landon.png
    bio: "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    email: fakemail@gmail.com
    twitter: https://twitter.com/Akzual1

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: icueMike
      avatar: /assets/images/memike.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Paginate
paginate: 6
