name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello there, thanks for opening your first issue. We welcome you to the community!'
        pr-message: 'Hello there, thanks for opening your first Pull Request. Someone will review it soon. Meanwhile if you have any questions or would just like to join us on discord, click <a href="https://discord.gg/4QJnGYVy6B">here</a>'
